#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
    /downloads \
    /incomplete-downloads

# permissions
chown -R abc:abc \
    /app \
    /config \
    /downloads \
    /incomplete-downloads
